### ISSUE TITLE
Implement a mobile menu

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/docs.rockylinux.org#2]
Currently there's just an icon -- needs to be a full menu

**Comment by ressonix** [comment]
I was unable to reproduce this, however if JavaScript is disabled in the browser the menu can't animate. I'm going to play around with CSS trickery and if that fails might have to resort to making a list style menu if JavaScript is disabled.

**Comment by hbjydev** [comment]
@ressonix What? This is to _create_ a mobile menu for the site, haha

**Comment by ressonix** [comment]
Oh wait, my bad. I didn't even realize this was the docs repo. 🤦‍♂️

**Comment by ressonix** [comment]
I can work on this later tonight. Did you want me to just implement the same menu we have on the main site and just change the logo area and the nav links?

**Comment by hbjydev** [comment]
Something pretty similar. Logo just needs replacing with the icon > text arrangement we've got now.

**Comment by hbjydev** [comment]
Eventually I'll split that stuff out into React component library.
