### ISSUE TITLE
fix or delete pre-commit CI config

### ISSUE THREAD

**Issue by NeilHanlon** [rocky-linux/docs.rockylinux.org#37]
https://results.pre-commit.ci/run/github/333151333/1646923587.XJiduhx4Q8ytfqO5S42xLw

=====> /tmp/tmpxoyqtujb/.pre-commit-config.yaml is not a file

**Comment by hbjydev** [comment]
@NeilHanlon Actually that looks more like it might be a problem with pre-commit ci

I can reach out to Anthony about that (or maybe ping him here)

**Comment by hbjydev** [comment]
@asottile Hey Anthony, sorry to bug you -- any idea what this might be?

**Comment by NeilHanlon** [comment]
I think it's just that there's no pre-commit config in the repo. wondering if it maybe got lost somewhere in the git history?

**Comment by hbjydev** [comment]
Possibly a good idea to remove it from this repo if it's added as an integration?

**Comment by hbjydev** [comment]
(Sorry for the ping Anthony, I realised that _far_ too late haha)
