### ISSUE TITLE
Add Documentation for Language (Hindi)

### ISSUE THREAD

**Issue by tnniras** [rocky-linux/docs.rockylinux.org#77]
Hello Team,
I love Rocky Linux and I would like to contribute for translating Rocky Linux Documentation . 

As a negative Hindi and Marathi  speaker, I'm confident that I can translate one page at a time. This will allow new linux users to onboard and obtain in depth knowledge of RockyLinux ecosystem.

Please let me know if I can get started.

Tushar

**Comment by NezSez** [comment]
Hey welcome tnniras, and thanks for the interest!
Here is a [Contribution Guide](https://docs.rockylinux.org/guides/contribute/#contribution-guide) for Rocky Linux Documentation. Here is a section on [Translation](https://docs.rockylinux.org/guides/contribute/#translation).
It's a bit of reading we know, so definitely ask questions in the [MatterMost Documentation channel](https://chat.rockylinux.org/rocky-linux/channels/documentation)

**Comment by sspencerwire** [comment]
> Hello Team, I love Rocky Linux and I would like to contribute for translating Rocky Linux Documentation .
> 
> As a negative Hindi and Marathi speaker, I'm confident that I can translate one page at a time. This will allow new linux users to onboard and obtain in depth knowledge of RockyLinux ecosystem.
> 
> Please let me know if I can get started.
> 
> Tushar

Hello Tushar!  Welcome. @SergeCroise notified me of your interest in translating. Thank you for that!  What I need to find out is if the language(s) you are actually proposing translations for are supported by both our Crowdin translation engine, and our material-mkdocs web engine. I'm traveling at the moment, so not in an environment where I can easily test the additions of languages in my local environment which duplicates the material-mkdocs environment. I will be back home an more available around November 7, so please be patient with me until after that. Thank you again, and welcome!! 

Steve

**Comment by sspencerwire** [comment]
@tnniras Just checked material-mkdocs. It looks like Hindi is available, but not Marathi. I'll need ot check Crowdin to make sure that engine will support Hindi as well, but there's no point in adding Marathi, since it isn't supported by the web engine. Again, all of this will take a little time, so be patient with us! :-)

**Comment by tnniras** [comment]
Hello Guys,
Thank you for quick response.  I will take a look at material-mkdocs. 

And l agree let's ignore Marathi Language for now.  So, excited to be part of this. Thanks again!  :)

**Comment by tnniras** [comment]
@SergeCroise 
I've seen you updated mkdocs.yml to add हिन्दी. I'm new to the reviews. Is it failed?
